CREATE DATABASE dogs;

USE dogs;

CREATE TABLE owners (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  PRIMARY KEY(id)
);

CREATE TABLE breeds (
  id INT NOT NULL AUTO_INCREMENT,
  breed VARCHAR(35),
  img VARCHAR(255),
  owner_id INT NOT NULL,
  PRIMARY KEY(id)
);